# Generated by Django 5.2.5 on 2025-10-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_user_bio_user_job_title_and_more'),
        ('job_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_current', to='job_roles.jobrole'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_job_roles',
            field=models.ManyToManyField(blank=True, related_name='users_targeting', to='job_roles.jobrole'),
        ),
    ]
