# Generated by Django 5.2.5 on 2025-10-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('issuer_name', models.CharField(max_length=255)),
                ('issuer_type', models.CharField(choices=[('PLATFORM', 'Online Platform'), ('UNIVERSITY', 'University'), ('COMPANY', 'Company'), ('ORGANIZATION', 'Organization'), ('GOVERNMENT', 'Government')], default='PLATFORM', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='certificate_providers', to='skills.skill')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='certificate_name_10a8c8_idx'), models.Index(fields=['issuer_name'], name='certificate_issuer__1fa83d_idx'), models.Index(fields=['is_popular'], name='certificate_is_popu_9be8bc_idx')],
            },
        ),
    ]
