# Generated by Django 5.2.5 on 2025-10-17 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(max_length=50)),
                ('filters', models.JSONField(default=dict)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('widget_config', models.JSONField(default=dict)),
                ('filters', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recruiter', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecruitmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('APPLICATION_ANALYSIS', 'Application Analysis'), ('CANDIDATE_PIPELINE', 'Candidate Pipeline'), ('TIME_TO_HIRE', 'Time to Hire'), ('SOURCE_ANALYSIS', 'Source Analysis'), ('SKILL_GAP_ANALYSIS', 'Skill Gap Analysis'), ('PERFORMANCE_DASHBOARD', 'Performance Dashboard'), ('CUSTOM', 'Custom')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('report_data', models.JSONField()),
                ('export_format', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=10, null=True)),
                ('exported_file', models.FileField(blank=True, null=True, upload_to='reports/exports/')),
                ('is_exported', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['recruiter', 'report_type'], name='analytics_r_recruit_741029_idx'), models.Index(fields=['generated_at'], name='analytics_r_generat_f83d98_idx')],
            },
        ),
    ]
