# Generated by Django 5.2.5 on 2025-10-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsexport',
            name='export_type',
            field=models.CharField(choices=[('APPLICATIONS', 'Applications'), ('CANDIDATES', 'Candidates'), ('JOBS', 'Jobs'), ('ANALYTICS', 'Analytics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='analyticsexport',
            name='format',
            field=models.CharField(choices=[('EXCEL', 'Excel'), ('CSV', 'CSV'), ('PDF', 'PDF'), ('JSON', 'JSON')], default='EXCEL', max_length=10),
        ),
        migrations.AlterField(
            model_name='recruitmentreport',
            name='report_data',
            field=models.JSONField(default=dict),
        ),
    ]
