# Generated by Django 5.2.5 on 2025-10-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('DATA', 'Data & Analytics'), ('DEVOPS', 'DevOps & Cloud'), ('CYBERSECURITY', 'Cybersecurity'), ('PROJECT_MGMT', 'Project Management'), ('DESIGN', 'Design & UX'), ('TESTING', 'Testing & QA'), ('SUPPORT', 'IT Support'), ('NETWORKING', 'Networking'), ('DATABASE', 'Database')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_in_demand', models.BooleanField(default=False)),
                ('remote_friendly', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='job_roles', to='skills.skill')),
            ],
            options={
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['title'], name='job_roles_j_title_f6cec2_idx'), models.Index(fields=['category'], name='job_roles_j_categor_4e9964_idx'), models.Index(fields=['is_in_demand'], name='job_roles_j_is_in_d_bcdb33_idx')],
            },
        ),
    ]
