# Generated by Django 5.2.5 on 2025-10-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nqf_level', models.IntegerField(choices=[(5, 'NQF Level 5 - Higher Certificate'), (6, 'NQF Level 6 - Diploma & Advanced Certificate'), (7, "NQF Level 7 - Bachelor's Degree & Advanced Diploma"), (8, 'NQF Level 8 - Honours Degree & Postgraduate Diploma'), (9, "NQF Level 9 - Master's Degree"), (10, 'NQF Level 10 - Doctoral Degree')])),
            ],
            options={
                'ordering': ['nqf_level', 'name'],
                'unique_together': {('name', 'nqf_level')},
            },
        ),
    ]
