# Generated by Django 5.2.5 on 2025-10-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_analysis',
            field=models.JSONField(blank=True, help_text='Detailed AI analysis of the application', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='AI-generated feedback for improvement', null=True),
        ),
    ]
