# Generated by Django 5.2.5 on 2025-10-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('degrees', '0001_initial'),
        ('jobs', '0002_job_skills_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='certificates_preferred',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='certificates.certificate'),
        ),
        migrations.AddField(
            model_name='job',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='courses_preferred',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='degrees.degree'),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Internship'), ('TEMPORARY', 'Temporary')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('ENTRY', 'Entry Level (0-2 years)'), ('MID', 'Mid Level (2-5 years)'), ('SENIOR', 'Senior Level (5+ years)'), ('LEAD', 'Lead/Manager')], default='MID', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(blank=True, help_text='Maximum annual salary in USD', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(blank=True, help_text='Minimum annual salary in USD', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('ONSITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=20),
        ),
    ]
