# Generated by Django 5.2.5 on 2025-10-18 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_providers', '0001_initial'),
        ('companies', '0002_alter_company_options_company_created_at_and_more'),
        ('degrees', '0001_initial'),
        ('jobs', '0003_alter_job_options_job_certificates_preferred_and_more'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='certificates_preferred',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='certificate_providers.certificateprovider'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employment_type'], name='jobs_job_employm_743f88_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['work_type'], name='jobs_job_work_ty_4ebff2_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_level'], name='jobs_job_experie_09027f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['closing_date'], name='jobs_job_closing_769c0f_idx'),
        ),
    ]
