# Generated by Django 5.2.5 on 2025-10-17 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('TECH', 'Technology'), ('FINANCE', 'Finance & Banking'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail & E-commerce'), ('MANUFACTURING', 'Manufacturing'), ('CONSULTING', 'Consulting'), ('MEDIA', 'Media & Entertainment'), ('TELECOM', 'Telecommunications'), ('TRANSPORT', 'Transportation & Logistics'), ('REAL_ESTATE', 'Real Estate'), ('ENERGY', 'Energy & Utilities'), ('OTHER', 'Other')], default='TECH', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
