# Generated by Django 5.2.5 on 2025-10-17 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SAJobMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('skills_required', models.JSONField()),
                ('average_salary_min', models.IntegerField()),
                ('average_salary_max', models.IntegerField()),
                ('location_demand', models.JSONField()),
                ('experience_level', models.CharField(max_length=50)),
                ('market_demand', models.DecimalField(decimal_places=2, max_digits=5)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('career_gap_months', models.IntegerField(default=0)),
                ('job_stability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('career_progression', models.JSONField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('institution_tier', models.CharField(blank=True, max_length=50)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('qualifications', models.JSONField(blank=True, null=True)),
                ('technical_skills', models.JSONField(blank=True, null=True)),
                ('soft_skills', models.JSONField(blank=True, null=True)),
                ('certifications', models.JSONField(blank=True, null=True)),
                ('achievements_count', models.IntegerField(default=0)),
                ('quantifiable_achievements', models.JSONField(blank=True, null=True)),
                ('leadership_experience', models.BooleanField(default=False)),
                ('management_experience', models.BooleanField(default=False)),
                ('industry_experience', models.JSONField(blank=True, null=True)),
                ('specialization_areas', models.JSONField(blank=True, null=True)),
                ('market_demand_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('communication_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('red_flags', models.JSONField(blank=True, null=True)),
                ('strength_indicators', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_analysis', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skills_match', models.JSONField()),
                ('salary_range', models.JSONField()),
                ('location', models.CharField(max_length=100)),
                ('match_reasons', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
    ]
