# Generated by Django 5.2.5 on 2025-10-24 22:40

import django.core.validators
import django.db.models.deletion
import resumes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_sajobmarketdata_resume_analysis_data_cvanalysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvanalysis',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobmatch',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobmatch',
            name='user',
        ),
        migrations.DeleteModel(
            name='SAJobMarketData',
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='analysis_data',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_role_matched',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='missing_skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills_detected',
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=resumes.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CVAnalysis',
        ),
        migrations.DeleteModel(
            name='JobMatch',
        ),
    ]
