# Generated by Django 5.2.5 on 2025-10-25 09:43

import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_resume_options_remove_resume_parsed_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=resumes.models.resume_upload_path),
        ),
    ]
